name: LapisLogin
version: ${project.version}
main: net.lapismc.lapislogin.LapisLogin
authors: [Dart2112]
description: Simple login plugin for offline mode servers
permissions:
  lapislogin.required:
    decsription: Players with this permission will be required to register
  lapislogin.admin:
    decsription: Allows you to deregister players with /resetpassword (Player)
commands:
  lapislogin:
    description: Use /lapislogin help for help
  login:
    description: Allows you to login to the server
  register:
    description: Allows you to register a password for future logins
  logout:
    description: Allows you to logout immediately instead of waiting for the timeout
  changepassword:
      description: Allows you to change your password
  resetpassword:
      description: Allows admins to remove other peoples passwords requiring them to re-register
